/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness / version */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All fund mandates (NAV snapshot) */
        get: operations["listFunds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/funds/{fundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single fund by id */
        get: operations["getFund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Macro / market strip items */
        get: operations["listMarketTicker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/market/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexed performance series (executive chart) */
        get: operations["getMarketPerformance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: string;
            message: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
        };
        /**
         * @description UI mandate traffic light
         * @enum {string}
         */
        MandateStatus: "in" | "watch" | "breach";
        Fund: {
            id: string;
            name: string;
            mandate: string;
            benchmark: string;
            nav: number;
            /** @description 1D NAV change in percent */
            navChange: number;
            /** @description Year-to-date return percent */
            ytd: number;
            status: components["schemas"]["MandateStatus"];
        };
        FundListResponse: {
            funds: components["schemas"]["Fund"][];
        };
        FundResponse: {
            fund: components["schemas"]["Fund"];
        };
        /** @enum {string} */
        TickerDirection: "up" | "down" | "neutral";
        TickerItem: {
            label: string;
            value: string;
            changeText: string;
            direction: components["schemas"]["TickerDirection"];
        };
        TickerResponse: {
            items: components["schemas"]["TickerItem"][];
        };
        PerformancePoint: {
            /** @description Month label */
            m: string;
            paramount: number;
            bond: number;
            mmf: number;
            asi: number;
            ntb: number;
        };
        PerformanceResponse: {
            points: components["schemas"]["PerformancePoint"][];
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        FundId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listFunds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fund list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundListResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getFund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fundId: components["parameters"]["FundId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fund */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    listMarketTicker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getMarketPerformance: {
        parameters: {
            query?: {
                /** @description Horizon label (server may ignore) */
                range?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monthly indexed points */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
